Readme
Financial-Times/kat-client-proxies pull request #7
Opened 2017-05-22 13:49 UTC by kateloschinina

Update README with the most relevant info.

2017-05-24 16:11 UTC, dapenguin requested changes

2017-05-24 16:11 UTC, dapenguin commented on README.md
> +KAT (Knowledge & administration tools) is a part of ft.com application created for Financial Times B2B clients.
Change "is a part of ft.com" to "is an ft.com"

2017-05-24 16:11 UTC, dapenguin commented on README.md
> +A library of client proxies for various APIs for KAT.
Change "APIs for KAT" to "APIs used by KAT"

2017-05-24 16:11 UTC, dapenguin commented on README.md
> +This component has been created to be included throughout other KAT components.
Similar to what we recently spoke about, consider whether "module" would be more appropriate than "component"

2017-05-24 16:17 UTC, kateloschinina commented on README.md
> +A library of client proxies for various APIs for KAT.
👍

2017-05-24 16:17 UTC, kateloschinina commented on README.md
> +KAT (Knowledge & administration tools) is a part of ft.com application created for Financial Times B2B clients.
👍

2017-05-24 16:18 UTC, kateloschinina commented on README.md
> +This component has been created to be included throughout other KAT components.
👍

2017-05-25 10:19 UTC, dapenguin submitted a review, later dismissed

2017-05-25 10:19 UTC, dapenguin commented on README.md
> +This module has been created to be included throughout other KAT components.
Should probably change the last word from "components" to "modules"

2017-05-25 10:19 UTC, dapenguin commented on README.md
>  If you want to update connected components with the latest version, you need to follow the following steps:
Feels like this line should also use "modules" instead of "components".

2017-05-25 10:19 UTC, dapenguin commented on README.md
>  2. Go to `package.json` file of the component you want to update, and change `"kat-client-proxies"` dependency version to the [newly released one](https://github.com/Financial-Times/kat-client-proxie
Feels like this line should also use "module" instead of "component".

2017-05-25 10:58 UTC, dapenguin approved these changes
👍

2017-05-25 11:01 UTC, merged